server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/testDB?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true



jwt:
  secret: dGhpcy1pcy1zZWN1cml0eS1wcmFjdGljZS1zZWNyZXQta2V5LW1hZGUtYnktamFlLWhlZS10aGlzLWtleS1uZWVkLW1vcmUtbG9uZy12ZXJzaW9uLW1vcmUtbW9yZS1sb25nCg==
  token-validity-in-seconds: 86400